### ISSUE TITLE
action method not working when using Form::....?

### ISSUE THREAD

**Issue by edwinheij** [inkvizytor/FluentForm#4]
``` php
Form::open()->action('search')
```

will give me a FatalErrorException:

> Method inkvizytor\FluentForm\Controls\Elements\Form::__toString() must not throw an exception

Is it a failure of am I not using it correctly? Tried a route-action and a route-name and a regular string.

**Comment by inkvizytor** [comment]
There was an error in action() method, it's fixed now. You should use action() like this:

``` php
Form::open()->action('UserController@create')
```

`Form::open()` has also route() and url() methods (route() accepts route name and url() accepts plain url).

**Comment by edwinheij** [comment]
Thanks, looks good. Will check this tonight.

**Comment by edwinheij** [comment]
Fixed
